site_name: Tkzsdwm's Notebook
dev_addr: '127.0.0.1:5500' #默认值
theme:
  name: 'material'
  custom_dir: docs/overrides
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: grey
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: white
      toggle:
        icon: material/weather-night 
        name: Switch to light mode
  language: 'zh'
  font: false
  plugins:
  - search
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Beijing
      enable_creation_date: true
  nav:
  - Home: docs/index.md
